In [1]:
import pandas as pd

### Read tennis datasets from kaggle as dataframes

In [2]:
data_path = "data/"
players_and_years = pd.read_csv(data_path+"players(man).csv")
players_tournament_results = pd.read_csv(data_path+"players_tournament(man).csv")
players_tournament_detailed = pd.read_csv(data_path+"raw_kaggle.csv")
players_tournament_serve_data = pd.read_csv(data_path+"serve_kaggle.csv")
players_tournament_return_data = pd.read_csv(data_path+"return_kaggle.csv")

In [3]:
players_and_years.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               462 non-null    object
 1   number_of_matches  462 non-null    int64
 2   playing_years      462 non-null    object
dtypes: int64(1), object(2)
memory usage: 11.0+ KB

In [4]:
players_and_years.head()

,name,number_of_matches,playing_years
0,Jannik Sinner,201,"[2019, 2020, 2021, 2022, 2023, 2024]"
1,Carlos Alcaraz,174,"[2019, 2020, 2021, 2022, 2023, 2024]"
2,Alexander Zverev,281,"[2014, 2015, 2016, 2017, 2018, 2019, 2020, 202..."
3,Novak Djokovic,577,"[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201..."
4,Daniil Medvedev,286,"[2016, 2017, 2018, 2019, 2020, 2021, 2022, 202..."

In [5]:
players_and_years["number_of_years"] = players_and_years["playing_years"].str.count(',') + 1

In [6]:
players_and_years.sort_values(by="number_of_matches", ascending=False).reset_index(drop=True)

,name,number_of_matches,playing_years,number_of_years
0,Novak Djokovic,577,"[2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...",20
1,Rafael Nadal,494,"[2003, 2004, 2005, 2006, 2007, 2008, 2009, 201...",22
2,Hubert Hurkacz,291,"[2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]",8
3,Daniil Medvedev,286,"[2016, 2017, 2018, 2019, 2020, 2021, 2022, 202...",9
4,Alexander Zverev,281,"[2014, 2015, 2016, 2017, 2018, 2019, 2020, 202...",11
...,...,...,...,...
457,Peter Bertran,1,[2022],1
458,Liam Draxl,1,[2024],1
459,Alastair Gray,1,[2022],1
460,Mate Valkusz,1,[2023],1
461,Jan Kumstat,1,[2024],1

In [7]:
players_tournament_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6422 entries, 0 to 6421
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        6422 non-null   object
 1   year        6422 non-null   int64
 2   tournament  6422 non-null   object
 3   rounds      6422 non-null   object
dtypes: int64(1), object(3)
memory usage: 200.8+ KB

In [8]:
players_tournament_results.head()

            name  year    tournament       rounds
0  Jannik Sinner  2019    Bergamo CH  ['QF', 'F']
1  Jannik Sinner  2019   Alicante CH      ['R64']
2  Jannik Sinner  2019    Ostrava CH        ['F']
3  Jannik Sinner  2019  Rome Masters      ['R64']
4  Jannik Sinner  2019       US Open     ['R128']

In [9]:
players_tournament_results["number_of_rounds"] = players_tournament_results["rounds"].str.count(",") + 1

In [10]:
players_tournament_results.sort_values(by="number_of_rounds", ascending=False).reset_index(drop=True)

,name,year,tournament,rounds,number_of_rounds
0,Botic Van De Zandschulp,2021,US Open,"['Q1', 'Q2', 'Q3', 'R128', 'R64', 'R32', 'R16'...",8
1,Carlos Alcaraz,2023,Wimbledon,"['R128', 'R64', 'R32', 'R16', 'QF', 'SF', 'F']",7
2,Daniil Medvedev,2023,US Open,"['R128', 'R64', 'R32', 'R16', 'QF', 'SF', 'F']",7
3,Jannik Sinner,2024,US Open,"['R128', 'R64', 'R32', 'R16', 'QF', 'SF', 'F']",7
4,Carlos Alcaraz,2024,Roland Garros,"['R128', 'R64', 'R32', 'R16', 'QF', 'SF', 'F']",7
...,...,...,...,...,...
6417,David Goffin,2016,Madrid Masters,['R64'],1
6418,David Goffin,2016,Monte Carlo Masters,['R16'],1
6419,David Goffin,2015,Davis Cup World Group F,['RR'],1
6420,David Goffin,2015,Paris Masters,['R16'],1
6421,Jan Kumstat,2024,Australian Open Juniors,['F'],1

In [11]:
players_tournament_detailed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237205 entries, 0 to 237204
Data columns (total 17 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Name        237205 non-null  object
 1   Date        237205 non-null  object
 2   Tournament  237205 non-null  object
 3   Surface     237177 non-null  object
 4   Rd          237205 non-null  object
 5   Rk          232817 non-null  float64
 6   vRk         226811 non-null  float64
 7   against     237205 non-null  object
 8   Score       237205 non-null  object
 9   TP          150406 non-null  float64
 10  Aces        150406 non-null  float64
 11  DFs         150406 non-null  float64
 12  SP          150406 non-null  float64
 13  1SP         150406 non-null  float64
 14  2SP         150406 non-null  float64
 15  vA          150406 non-null  float64
 16  Time        144246 non-null  object
dtypes: float64(9), object(8)
memory usage: 30.8+ MB

In [12]:
players_tournament_detailed.head()

,Name,Date,Tournament,Surface,Rd,Rk,vRk,against,Score,TP,Aces,DFs,SP,1SP,2SP,vA,Time
0,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,F,1.0,4.0,"['(1)Sinner', '(4)NovakDjokovic[SRB]']",7-6(4) 6-3,125.0,8.0,0.0,67.0,41.0,26.0,4.0,1:37
1,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,SF,1.0,33.0,"['(1)Sinner', '(30)TomasMachac[CZE]']",6-4 7-5,138.0,10.0,1.0,69.0,46.0,23.0,5.0,1:43
2,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,QF,1.0,5.0,"['(1)Sinner', '(5)DaniilMe', 'e', 'v[RUS]']",6-1 6-4,108.0,9.0,0.0,50.0,33.0,17.0,3.0,1:24
3,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,R16,1.0,16.0,"['(1)Sinner', '(14)BenShelton[USA]']",6-4 7-6(1),124.0,7.0,0.0,66.0,46.0,20.0,7.0,1:28
4,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,R32,1.0,37.0,"['(1)Sinner', '(31)TomasMartinEtcheverry[ARG]']",6-7(3) 6-4 6-2,186.0,12.0,1.0,92.0,64.0,28.0,11.0,2:39

In [13]:
djokovic_sh_24 = players_tournament_detailed[players_tournament_detailed.Name.str.contains("Djokovic") 
& players_tournament_detailed.Tournament.str.contains("Shanghai") 
& players_tournament_detailed.Date.str.contains("2024")]
djokovic_sh_24

,Name,Date,Tournament,Surface,Rd,Rk,vRk,against,Score,TP,Aces,DFs,SP,1SP,2SP,vA,Time
1568,Novak Djokovic,2-Oct-2024,Shanghai Masters,Hard,F,4.0,1.0,"['(1)JannikSinner[ITA]', '(4)Djokovic']",7-6(4) 6-3,125.0,4.0,0.0,58.0,38.0,20.0,8.0,1:37
1569,Novak Djokovic,2-Oct-2024,Shanghai Masters,Hard,SF,4.0,7.0,"['(4)Djokovic', '(7)TaylorFritz[USA]']",6-4 7-6(6),155.0,7.0,0.0,71.0,50.0,21.0,6.0,1:56
1570,Novak Djokovic,2-Oct-2024,Shanghai Masters,Hard,QF,4.0,65.0,"['(4)Djokovic', 'JakubMensik[CZE]']",6-7(4) 6-1 6-4,191.0,7.0,1.0,82.0,52.0,30.0,17.0,2:19
1571,Novak Djokovic,2-Oct-2024,Shanghai Masters,Hard,R16,4.0,61.0,"['(4)Djokovic', 'RomanSafiullin[RUS]']",6-3 6-2,94.0,4.0,1.0,51.0,33.0,18.0,2.0,1:13
1572,Novak Djokovic,2-Oct-2024,Shanghai Masters,Hard,R32,4.0,30.0,"['(4)Djokovic', '(28)FlavioCobolli[ITA]']",6-1 6-2,95.0,3.0,2.0,40.0,24.0,16.0,3.0,1:03
1573,Novak Djokovic,2-Oct-2024,Shanghai Masters,Hard,R64,4.0,43.0,"['(4)Djokovic', 'AlexMichelsen[USA]']",7-6(3) 7-6(9),162.0,7.0,3.0,76.0,52.0,24.0,10.0,1:55

In [14]:
djokovic_sh_24[["Name", "TP", "Aces", "DFs", "SP", "1SP", "2SP", "vA"]].groupby("Name").mean()

                   TP      Aces       DFs    SP   1SP   2SP        vA
Name
Novak Djokovic  137.0  5.333333  1.166667  63.0  41.5  21.5  7.666667

In [15]:
alcaraz_ma_24 = players_tournament_detailed[players_tournament_detailed.Name.str.contains("Alcaraz") 
& players_tournament_detailed.Tournament.str.contains("Madrid") 
& players_tournament_detailed.Date.str.contains("2024")]
alcaraz_ma_24

,Name,Date,Tournament,Surface,Rd,Rk,vRk,against,Score,TP,Aces,DFs,SP,1SP,2SP,vA,Time
486,Carlos Alcaraz,22-Apr-2024,Madrid Masters,Clay,QF,3.0,8.0,"['(7)An', 'eyRublev[RUS]', '(2)Alcaraz']",4-6 6-3 6-2,167.0,1.0,2.0,81.0,57.0,24.0,5.0,1:59
487,Carlos Alcaraz,22-Apr-2024,Madrid Masters,Clay,R16,3.0,24.0,"['(2)Alcaraz', '(23)JanLennar', 'truff[GER]']",6-3 6-7(5) 7-6(4),234.0,3.0,4.0,131.0,83.0,48.0,10.0,2:52
488,Carlos Alcaraz,22-Apr-2024,Madrid Masters,Clay,R32,3.0,63.0,"['(2)Alcaraz', 'ThiagoSeybothWil', 'BRA]']",6-3 6-3,107.0,2.0,1.0,46.0,31.0,15.0,3.0,1:15
489,Carlos Alcaraz,22-Apr-2024,Madrid Masters,Clay,R64,3.0,59.0,"['(2)Alcaraz', 'Alexan', 'rShevchenko[KAZ]']",6-2 6-1,93.0,1.0,0.0,38.0,26.0,12.0,0.0,1:08

In [16]:
alcaraz_ma_24[["Name", "TP", "Aces", "DFs", "SP", "1SP", "2SP", "vA"]].groupby("Name").mean()

                    TP  Aces   DFs    SP    1SP    2SP   vA
Name
Carlos Alcaraz  150.25  1.75  1.75  74.0  49.25  24.75  4.5

In [17]:
players_tournament_serve_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237185 entries, 0 to 237184
Data columns (total 17 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Name       237185 non-null  object
 1   Date       237185 non-null  object
 2   Tournment  237185 non-null  object
 3   Surface    237157 non-null  object
 4   Rd         237185 non-null  object
 5   Rk         232797 non-null  float64
 6   vRk        226791 non-null  float64
 7   against    237185 non-null  object
 8   Score      237185 non-null  object
 9   Dr         150366 non-null  object
 10  A%         150366 non-null  object
 11  Df%        150366 non-null  object
 12  1stIn      150366 non-null  object
 13  1st%       150366 non-null  object
 14  2nd%       150366 non-null  object
 15  Bpsvd      150366 non-null  object
 16  Time       144206 non-null  object
dtypes: float64(2), object(15)
memory usage: 30.8+ MB

In [18]:
players_tournament_serve_data.head()

,Name,Date,Tournment,Surface,Rd,Rk,vRk,against,Score,Dr,A%,Df%,1stIn,1st%,2nd%,Bpsvd,Time
0,Jannik Sinner,2‑Oct‑2024,Shanghai Masters,Hard,F,1.0,4.0,"['(1)Sinner', '(4)NovakDjokovic[SRB]']",7-6(4) 6-3,1.03,11.9%,0.0%,61.2%,75.6%,65.4%,0/0,1:37
1,Jannik Sinner,2‑Oct‑2024,Shanghai Masters,Hard,SF,1.0,33.0,"['(1)Sinner', '(30)TomasMachac[CZE]']",6-4 7-5,1.33,14.5%,1.4%,66.7%,73.9%,60.9%,2/3,1:43
2,Jannik Sinner,2‑Oct‑2024,Shanghai Masters,Hard,QF,1.0,5.0,"['(1)Sinner', '(5)DaniilMe', 'e', 'v[RUS]']",6-1 6-4,1.94,18.0%,0.0%,66.0%,84.8%,58.8%,1/1,1:24
3,Jannik Sinner,2‑Oct‑2024,Shanghai Masters,Hard,R16,1.0,16.0,"['(1)Sinner', '(14)BenShelton[USA]']",6-4 7-6(1),1.31,10.6%,0.0%,69.7%,87.0%,65.0%,7/7,1:28
4,Jannik Sinner,2‑Oct‑2024,Shanghai Masters,Hard,R32,1.0,37.0,"['(1)Sinner', '(31)TomasMartinEtcheverry[ARG]']",6-7(3) 6-4 6-2,1.30,13.0%,1.1%,69.6%,78.1%,53.6%,4/5,2:39

In [19]:
nishikori_mi_24 = players_tournament_serve_data[players_tournament_serve_data.Name.str.contains("Nishikori") 
& players_tournament_serve_data.Tournment.str.contains("Miami") 
& players_tournament_serve_data.Date.str.contains("2024")]
nishikori_mi_24

,Name,Date,Tournment,Surface,Rd,Rk,vRk,against,Score,Dr,A%,Df%,1stIn,1st%,2nd%,Bpsvd,Time
76352,Kei Nishikori,18‑Mar‑2024,Miami Masters,Hard,R128,351.0,40.0,"['SebastianOfner[AUT]', '(WC)Nishikori']",6-3 6-4,0.73,0.0%,0.0%,64.9%,59.5%,70.0%,2/4,1:19

In [20]:
players_tournament_return_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237196 entries, 0 to 237195
Data columns (total 17 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Name        237196 non-null  object
 1   Date        237196 non-null  object
 2   Tournament  237196 non-null  object
 3   Surface     237168 non-null  object
 4   Rd          237196 non-null  object
 5   Rk          232808 non-null  float64
 6   vRk         226802 non-null  float64
 7   against     0 non-null       float64
 8   Score       237196 non-null  object
 9   DR          150390 non-null  object
 10  TPW         150390 non-null  object
 11  RPW         150390 non-null  object
 12  vA%         150390 non-null  object
 13  v1st%       150390 non-null  object
 14  v2nd%       150390 non-null  object
 15  BPCnv       150390 non-null  object
 16  Time        144230 non-null  object
dtypes: float64(3), object(14)
memory usage: 30.8+ MB

In [21]:
players_tournament_return_data.head()

,Name,Date,Tournament,Surface,Rd,Rk,vRk,against,Score,DR,TPW,RPW,vA%,v1st%,v2nd%,BPCnv,Time
0,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,F,1.0,4.0,NaN,7-6(4) 6-3,1.03,52.0%,29.3%,6.9%,23.7%,40.0%,1/2,1:37
1,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,SF,1.0,33.0,NaN,6-4 7-5,1.33,55.1%,40.6%,7.2%,35.6%,50.0%,3/7,1:43
2,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,QF,1.0,5.0,NaN,6-1 6-4,1.94,60.2%,46.6%,5.2%,19.4%,77.8%,3/4,1:24
3,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,R16,1.0,16.0,NaN,6-4 7-6(1),1.31,54.8%,25.9%,12.1%,14.0%,60.0%,1/1,1:28
4,Jannik Sinner,2-Oct-2024,Shanghai Masters,Hard,R32,1.0,37.0,NaN,6-7(3) 6-4 6-2,1.30,54.3%,38.3%,11.7%,16.3%,62.2%,4/13,2:39

In [25]:
rublev_us_24 = players_tournament_return_data[players_tournament_return_data.Name.str.contains("Rublev") 
& players_tournament_return_data.Tournament.str.contains("US Open") 
& players_tournament_return_data.Date.str.contains("2024")]
rublev_us_24

,Name,Date,Tournament,Surface,Rd,Rk,vRk,against,Score,DR,TPW,RPW,vA%,v1st%,v2nd%,BPCnv,Time
4387,Andrey Rublev,26-Aug-2024,US Open,Hard,R16,6.0,9.0,NaN,6-3 7-6(3) 1-6 3-6 6-3,1.11,49.7%,36.4%,9.8%,20.2%,58.1%,5/18,3:39
4388,Andrey Rublev,26-Aug-2024,US Open,Hard,R32,6.0,38.0,NaN,6-3 7-5 6-4,1.47,55.6%,43.5%,13.9%,37.1%,52.2%,5/16,2:03
4389,Andrey Rublev,26-Aug-2024,US Open,Hard,R64,6.0,56.0,NaN,4-6 5-7 6-1 6-2 6-2,1.21,54.5%,45.5%,12.4%,32.1%,61.2%,9/23,4:06
4390,Andrey Rublev,26-Aug-2024,US Open,Hard,R128,6.0,68.0,NaN,6-3 7-6(3) 7-5,1.82,56.5%,38.1%,5.7%,29.6%,47.1%,4/6,2:20